export const assessmentCatalog = [
  {
    id: 'programming',
    title: 'Programming',
    category: 'Programming',
    difficulty: 'Intermediate',
    questionCount: 6,
    duration: 1800,
    estimatedTime: '30 min',
    description: 'Evaluate core coding fundamentals, logic flow, and practical implementation choices.',
    questions: [
      {
        id: 1,
        category: 'Programming',
        difficulty: 'Easy',
        question: 'Which JavaScript concept is used to handle asynchronous operations in a cleaner way?',
        options: ['Callbacks', 'Promises', 'Loops', 'Variables'],
        correctAnswer: 'Promises',
        explanation: 'Promises provide a structured way to manage async work and avoid callback hell.',
      },
      {
        id: 2,
        category: 'Programming',
        difficulty: 'Medium',
        question: 'What is the primary purpose of a React component?',
        options: ['To manage server storage', 'To render UI', 'To connect to a database', 'To compile CSS'],
        correctAnswer: 'To render UI',
        explanation: 'React components define a reusable portion of the user interface.',
      },
      {
        id: 3,
        category: 'Programming',
        difficulty: 'Easy',
        question: 'Which keyword creates a block-scoped variable in JavaScript?',
        options: ['var', 'let', 'const', 'function'],
        correctAnswer: 'let',
        explanation: 'let introduces a block-scoped variable that is not hoisted like var.',
      },
      {
        id: 4,
        category: 'Programming',
        difficulty: 'Medium',
        question: 'What does the map() method do on an array?',
        options: ['Filters values', 'Modifies the existing array in place', 'Creates a new array from transformed values', 'Sorts values descending'],
        correctAnswer: 'Creates a new array from transformed values',
        explanation: 'map() transforms each element and returns a new array without mutating the original.',
      },
      {
        id: 5,
        category: 'Programming',
        difficulty: 'Medium',
        question: 'Which HTML tag is used to define a section of content?',
        options: ['<div>', '<span>', '<section>', '<article>'],
        correctAnswer: '<section>',
        explanation: 'The section element semantically defines a thematic grouping of content.',
      },
      {
        id: 6,
        category: 'Programming',
        difficulty: 'Hard',
        question: 'What is the purpose of a dependency injection pattern?',
        options: ['Increase page load speed', 'Reduce network usage', 'Provide dependencies from the outside', 'Hide HTML content'],
        correctAnswer: 'Provide dependencies from the outside',
        explanation: 'Dependency injection makes components easier to test and decouple logic from concrete implementations.',
      },
    ],
  },
  {
    id: 'dsa',
    title: 'DSA',
    category: 'DSA',
    difficulty: 'Hard',
    questionCount: 6,
    duration: 2100,
    estimatedTime: '35 min',
    description: 'Assess algorithmic thinking, data structures, and problem solving under time pressure.',
    questions: [
      {
        id: 1,
        category: 'DSA',
        difficulty: 'Easy',
        question: 'What is the time complexity of accessing an element in an array by index?',
        options: ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'],
        correctAnswer: 'O(1)',
        explanation: 'Array indexing is constant time in most languages because the element is directly addressed.',
      },
      {
        id: 2,
        category: 'DSA',
        difficulty: 'Medium',
        question: 'Which data structure follows the LIFO principle?',
        options: ['Queue', 'Graph', 'Stack', 'Heap'],
        correctAnswer: 'Stack',
        explanation: 'A stack processes elements in last-in-first-out order.',
      },
      {
        id: 3,
        category: 'DSA',
        difficulty: 'Medium',
        question: 'Which traversal visits the root before its subtrees?',
        options: ['Postorder', 'Level order', 'Inorder', 'Preorder'],
        correctAnswer: 'Preorder',
        explanation: 'Preorder traversal processes the node before traversing child nodes.',
      },
      {
        id: 4,
        category: 'DSA',
        difficulty: 'Hard',
        question: 'What is the average time complexity of binary search?',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
        correctAnswer: 'O(log n)',
        explanation: 'Binary search halves the search space at each step.',
      },
      {
        id: 5,
        category: 'DSA',
        difficulty: 'Medium',
        question: 'What is a linked list best suited for?',
        options: ['Constant-time random access', 'Fast array sorting', 'Dynamic insertion and deletion', 'Static memory layout'],
        correctAnswer: 'Dynamic insertion and deletion',
        explanation: 'Linked lists handle insertions and deletions efficiently without reallocation.',
      },
      {
        id: 6,
        category: 'DSA',
        difficulty: 'Hard',
        question: 'Which approach is used to avoid recomputation in overlapping subproblems?',
        options: ['Greedy', 'Recursion', 'Memoization', 'Indexing'],
        correctAnswer: 'Memoization',
        explanation: 'Memoization stores previously computed values to avoid repeated work.',
      },
    ],
  },
  {
    id: 'dbms',
    title: 'DBMS',
    category: 'DBMS',
    difficulty: 'Intermediate',
    questionCount: 6,
    duration: 1800,
    estimatedTime: '30 min',
    description: 'Measure your understanding of relational databases, schema design, and query logic.',
    questions: [
      {
        id: 1,
        category: 'DBMS',
        difficulty: 'Easy',
        question: 'Which key uniquely identifies a row in a table?',
        options: ['Foreign key', 'Primary key', 'Unique key', 'Composite key'],
        correctAnswer: 'Primary key',
        explanation: 'A primary key uniquely identifies each record in a table.',
      },
      {
        id: 2,
        category: 'DBMS',
        difficulty: 'Medium',
        question: 'What does JOIN do in SQL?',
        options: ['Combines tables', 'Creates indexes', 'Deletes rows', 'Changes schemas'],
        correctAnswer: 'Combines tables',
        explanation: 'JOIN combines rows from two or more tables using a related column.',
      },
      {
        id: 3,
        category: 'DBMS',
        difficulty: 'Easy',
        question: 'Which clause filters rows after grouping?',
        options: ['WHERE', 'ORDER BY', 'HAVING', 'GROUP BY'],
        correctAnswer: 'HAVING',
        explanation: 'HAVING filters grouped results after aggregation.',
      },
      {
        id: 4,
        category: 'DBMS',
        difficulty: 'Medium',
        question: 'Normalization helps reduce what issue?',
        options: ['Latency', 'Redundancy', 'Concurrency', 'Indexes'],
        correctAnswer: 'Redundancy',
        explanation: 'Normalization organizes data to reduce duplicated information and anomalies.',
      },
      {
        id: 5,
        category: 'DBMS',
        difficulty: 'Medium',
        question: 'Which statement removes all rows from a table but keeps the table structure?',
        options: ['DELETE', 'DROP', 'TRUNCATE', 'ALTER'],
        correctAnswer: 'TRUNCATE',
        explanation: 'TRUNCATE removes rows quickly while preserving the table definition.',
      },
      {
        id: 6,
        category: 'DBMS',
        difficulty: 'Hard',
        question: 'A foreign key references what?',
        options: ['A local variable', 'Another table’s primary key', 'A trigger', 'An index'],
        correctAnswer: 'Another table’s primary key',
        explanation: 'A foreign key links a row in one table to a row in another table.',
      },
    ],
  },
  {
    id: 'operating-systems',
    title: 'Operating Systems',
    category: 'Operating Systems',
    difficulty: 'Intermediate',
    questionCount: 6,
    duration: 1800,
    estimatedTime: '30 min',
    description: 'Test your grasp of processes, memory, scheduling, and concurrency.',
    questions: [
      {
        id: 1,
        category: 'Operating Systems',
        difficulty: 'Easy',
        question: 'What is a process?',
        options: ['A program in execution', 'A file in storage', 'A network protocol', 'A CPU register'],
        correctAnswer: 'A program in execution',
        explanation: 'A process is an active execution instance of a program.',
      },
      {
        id: 2,
        category: 'Operating Systems',
        difficulty: 'Medium',
        question: 'Which scheduler selects the next process to run?',
        options: ['Memory manager', 'CPU scheduler', 'Page replacement', 'File system'],
        correctAnswer: 'CPU scheduler',
        explanation: 'The CPU scheduler decides which runnable process gets CPU time next.',
      },
      {
        id: 3,
        category: 'Operating Systems',
        difficulty: 'Easy',
        question: 'What does deadlock mean?',
        options: ['A process is waiting indefinitely for resources', 'A CPU is overclocked', 'A file is missing', 'A program is compiled'],
        correctAnswer: 'A process is waiting indefinitely for resources',
        explanation: 'Deadlock occurs when processes wait on each other for resources that will never be released.',
      },
      {
        id: 4,
        category: 'Operating Systems',
        difficulty: 'Medium',
        question: 'What does paging help with?',
        options: ['Managing memory efficiently', 'Boosting internet speed', 'Optimizing databases', 'Increasing hard drive size'],
        correctAnswer: 'Managing memory efficiently',
        explanation: 'Paging allows memory to be managed in fixed-size units and reduces fragmentation.',
      },
      {
        id: 5,
        category: 'Operating Systems',
        difficulty: 'Medium',
        question: 'Which concept allows multiple processes to share CPU time?',
        options: ['Multiprocessing', 'Multitasking', 'Indexing', 'Compiling'],
        correctAnswer: 'Multitasking',
        explanation: 'Multitasking divides CPU time among processes to give the appearance of simultaneous execution.',
      },
      {
        id: 6,
        category: 'Operating Systems',
        difficulty: 'Hard',
        question: 'What is the role of a semaphore?',
        options: ['To manage network packets', 'To coordinate access to shared resources', 'To format disks', 'To compress files'],
        correctAnswer: 'To coordinate access to shared resources',
        explanation: 'Semaphores are synchronization primitives used to manage access to shared resources.',
      },
    ],
  },
  {
    id: 'computer-networks',
    title: 'Computer Networks',
    category: 'Computer Networks',
    difficulty: 'Intermediate',
    questionCount: 6,
    duration: 1800,
    estimatedTime: '30 min',
    description: 'Check your understanding of networking layers, routing, and data transfer.',
    questions: [
      {
        id: 1,
        category: 'Computer Networks',
        difficulty: 'Easy',
        question: 'What does IP stand for?',
        options: ['Internet Process', 'Internet Protocol', 'Internal Packet', 'Integrated Port'],
        correctAnswer: 'Internet Protocol',
        explanation: 'IP is the protocol used for routing packets across networks.',
      },
      {
        id: 2,
        category: 'Computer Networks',
        difficulty: 'Medium',
        question: 'Which layer is responsible for end-to-end communication?',
        options: ['Application', 'Transport', 'Network', 'Data Link'],
        correctAnswer: 'Transport',
        explanation: 'The transport layer provides reliable end-to-end delivery of data.',
      },
      {
        id: 3,
        category: 'Computer Networks',
        difficulty: 'Easy',
        question: 'What is a router used for?',
        options: ['To connect devices within a room', 'To forward packets between networks', 'To store passwords', 'To compile code'],
        correctAnswer: 'To forward packets between networks',
        explanation: 'Routers direct data between different networks based on routing rules.',
      },
      {
        id: 4,
        category: 'Computer Networks',
        difficulty: 'Medium',
        question: 'What does DNS do?',
        options: ['Compresses files', 'Translates domain names to IP addresses', 'Creates packets', 'Encrypts passwords'],
        correctAnswer: 'Translates domain names to IP addresses',
        explanation: 'DNS maps human-readable domain names to machine-readable IP addresses.',
      },
      {
        id: 5,
        category: 'Computer Networks',
        difficulty: 'Medium',
        question: 'Which protocol is commonly used for secure web browsing?',
        options: ['HTTP', 'FTP', 'HTTPS', 'SMTP'],
        correctAnswer: 'HTTPS',
        explanation: 'HTTPS uses encryption to protect web traffic between client and server.',
      },
      {
        id: 6,
        category: 'Computer Networks',
        difficulty: 'Hard',
        question: 'What is the purpose of TCP?',
        options: ['To ensure reliable ordered delivery', 'To format web pages', 'To manage memory', 'To compile applications'],
        correctAnswer: 'To ensure reliable ordered delivery',
        explanation: 'TCP provides connection-oriented, reliable transmission of data.',
      },
    ],
  },
  {
    id: 'sql',
    title: 'SQL',
    category: 'SQL',
    difficulty: 'Intermediate',
    questionCount: 6,
    duration: 1800,
    estimatedTime: '30 min',
    description: 'Assess querying skills, joins, filters, and database manipulation fluency.',
    questions: [
      {
        id: 1,
        category: 'SQL',
        difficulty: 'Easy',
        question: 'Which clause is used to retrieve rows from a table?',
        options: ['SELECT', 'INSERT', 'UPDATE', 'DELETE'],
        correctAnswer: 'SELECT',
        explanation: 'SELECT is used to read data from one or more tables.',
      },
      {
        id: 2,
        category: 'SQL',
        difficulty: 'Medium',
        question: 'What does the WHERE clause do?',
        options: ['Sorts results', 'Filters rows', 'Creates tables', 'Drops rows'],
        correctAnswer: 'Filters rows',
        explanation: 'WHERE limits the result set to rows that satisfy a condition.',
      },
      {
        id: 3,
        category: 'SQL',
        difficulty: 'Easy',
        question: 'Which SQL statement inserts new rows?',
        options: ['SELECT', 'INSERT', 'UPDATE', 'DELETE'],
        correctAnswer: 'INSERT',
        explanation: 'INSERT adds new records into a table.',
      },
      {
        id: 4,
        category: 'SQL',
        difficulty: 'Medium',
        question: 'Which SQL command changes existing data?',
        options: ['UPDATE', 'INSERT', 'SELECT', 'CREATE'],
        correctAnswer: 'UPDATE',
        explanation: 'UPDATE modifies existing rows in a table.',
      },
      {
        id: 5,
        category: 'SQL',
        difficulty: 'Medium',
        question: 'Which clause sorts results in descending order?',
        options: ['ORDER BY DESC', 'WHERE DESC', 'GROUP BY DESC', 'SORT DESC'],
        correctAnswer: 'ORDER BY DESC',
        explanation: 'ORDER BY DESC sorts the returned rows in descending order.',
      },
      {
        id: 6,
        category: 'SQL',
        difficulty: 'Hard',
        question: 'What is a subquery?',
        options: ['An index', 'A query inside another query', 'A transaction', 'A stored procedure'],
        correctAnswer: 'A query inside another query',
        explanation: 'A subquery is a query nested within another SQL statement.',
      },
    ],
  },
  {
    id: 'aptitude',
    title: 'Aptitude',
    category: 'Aptitude',
    difficulty: 'Easy',
    questionCount: 6,
    duration: 1500,
    estimatedTime: '25 min',
    description: 'Measure reasoning, logical consistency, and quantitative problem solving skills.',
    questions: [
      {
        id: 1,
        category: 'Aptitude',
        difficulty: 'Easy',
        question: 'If 5 pens cost ₹75, what is the cost of 1 pen?',
        options: ['₹10', '₹12', '₹15', '₹20'],
        correctAnswer: '₹15',
        explanation: 'Divide the total cost by the number of pens: 75 / 5 = 15.',
      },
      {
        id: 2,
        category: 'Aptitude',
        difficulty: 'Medium',
        question: 'Find the next number in the sequence: 2, 4, 8, 16, ?',
        options: ['18', '24', '32', '64'],
        correctAnswer: '32',
        explanation: 'Each number doubles, so the next term is 32.',
      },
      {
        id: 3,
        category: 'Aptitude',
        difficulty: 'Easy',
        question: 'If A is taller than B and B is taller than C, who is tallest?',
        options: ['A', 'B', 'C', 'Cannot say'],
        correctAnswer: 'A',
        explanation: 'Since A is taller than B and B is taller than C, A is tallest.',
      },
      {
        id: 4,
        category: 'Aptitude',
        difficulty: 'Medium',
        question: 'A train travels 60 km in 1 hour. How far in 3 hours?',
        options: ['120 km', '150 km', '180 km', '200 km'],
        correctAnswer: '180 km',
        explanation: 'Distance equals speed multiplied by time: 60 × 3 = 180 km.',
      },
      {
        id: 5,
        category: 'Aptitude',
        difficulty: 'Medium',
        question: 'Which word does not belong: Apple, Mango, Carrot, Banana?',
        options: ['Apple', 'Mango', 'Carrot', 'Banana'],
        correctAnswer: 'Carrot',
        explanation: 'Carrot is a vegetable while the others are fruits.',
      },
      {
        id: 6,
        category: 'Aptitude',
        difficulty: 'Hard',
        question: 'If 3 workers complete a task in 6 days, how many days would 6 workers take?',
        options: ['2 days', '3 days', '4 days', '6 days'],
        correctAnswer: '3 days',
        explanation: 'More workers reduce the time required, so 6 workers need 3 days.',
      },
    ],
  },
];

export function getAssessmentById(id) {
  return assessmentCatalog.find((assessment) => assessment.id === id) || assessmentCatalog[0];
}
