/**
 * SkillTrace AI - Module 11 Reports Data Store
 * Realistic mock datasets for Career Intelligence Reports:
 * 1. Portfolio Analysis Report
 * 2. Skill Assessment Report
 * 3. Career Recommendation Report
 * 4. Placement Prediction Report
 * 
 * Also contains historical report logs, skill gap analysis, and AI recommendation rules.
 * Structured for easy FastAPI + MongoDB + ML pipeline mapping in production.
 */

export const studentInfo = {
  name: 'Aditi Sharma',
  department: 'Computer Science & Engineering',
  batch: '2023 - 2027',
  currentSemester: 'Semester 7',
  targetRole: 'Full Stack Engineer',
  overallReadiness: 89,
};

export const reportTypes = [
  { id: 'portfolio-analysis', name: 'Portfolio Analysis', icon: 'FiFolder', color: '#0F9D8C' },
  { id: 'skill-assessment', name: 'Skill Assessment', icon: 'FiCheckSquare', color: '#3B82F6' },
  { id: 'career-recommendation', name: 'Career Recommendation', icon: 'FiCompass', color: '#8B5CF6' },
  { id: 'placement-prediction', name: 'Placement Prediction', icon: 'FiTarget', color: '#F5A623' },
];

export const primaryReportsData = {
  'portfolio-analysis': {
    id: 'rep-portfolio-001',
    type: 'portfolio-analysis',
    title: 'Comprehensive Portfolio Readiness Analysis',
    subtitle: 'Code quality, repository structure, GitHub activity, and project depth evaluation.',
    score: 87,
    maxScore: 100,
    scoreLabel: 'Portfolio Rating',
    scoreTag: 'Top 10% Batch',
    status: 'Completed',
    lastGenerated: 'Aug 11, 2026',
    generatedTimeAgo: '1 day ago',
    confidenceLevel: 94,
    badgeColor: 'success',
    keyInsights: [
      'GitHub repository commit velocity increased by 35% in the last 60 days.',
      'Strong React and Node.js architecture present in flagship projects.',
      'Documentation quality is rated 88/100 with clear setup instructions and architecture diagrams.',
      'Unit test coverage remains low (< 20%) across 3 out of 5 featured repositories.',
    ],
    strengths: [
      'Modular Component Architecture',
      'Consistent Git Commit History',
      'Production-Ready UI UX',
      'Clean Code & File Layout',
    ],
    weaknesses: [
      'Low Unit & Integration Test Coverage',
      'Missing Docker / CI-CD Deployment Workflows',
      'Limited Microservice / Backend Scalability Benchmarks',
    ],
    recommendations: [
      {
        id: 'rec-p1',
        title: 'Add automated Jest/Playwright tests to main repository',
        priority: 'High',
        impact: '+ 5 pts',
        category: 'Quality',
        actionText: 'View Guide',
      },
      {
        id: 'rec-p2',
        title: 'Containerize Backend API using Docker & Compose',
        priority: 'High',
        impact: '+ 4 pts',
        category: 'DevOps',
        actionText: 'Setup Docker',
      },
      {
        id: 'rec-p3',
        title: 'Add Live Demo URLs and API Swagger Docs to READMEs',
        priority: 'Medium',
        impact: '+ 3 pts',
        category: 'Documentation',
        actionText: 'Update Docs',
      },
    ],
    subMetrics: [
      { name: 'Technical Depth', value: 91, label: '91/100', color: '#0F9D8C' },
      { name: 'Documentation Quality', value: 84, label: '84/100', color: '#3B82F6' },
      { name: 'Git Commit Consistency', value: 92, label: '92/100', color: '#8B5CF6' },
      { name: 'Test & DevOps Readiness', value: 65, label: '65/100', color: '#F5A623' },
    ],
    skillGaps: [
      { skill: 'Docker Containerization', impact: 'High', currentLevel: 'Beginner', requiredLevel: 'Intermediate', estHours: 12 },
      { skill: 'GitHub Actions CI/CD', impact: 'High', currentLevel: 'None', requiredLevel: 'Intermediate', estHours: 15 },
      { skill: 'Jest / Testing Library', impact: 'Medium', currentLevel: 'Beginner', requiredLevel: 'Intermediate', estHours: 10 },
      { skill: 'GraphQL APIs', impact: 'Low', currentLevel: 'None', requiredLevel: 'Basic', estHours: 8 },
    ],
    chartData: {
      type: 'radar',
      labels: ['Code Depth', 'Documentation', 'Git Activity', 'UI/UX Polish', 'DevOps & Testing', 'Architecture'],
      values: [91, 84, 92, 89, 65, 88],
    },
    secondaryChartData: {
      type: 'bar',
      labels: ['React Suite', 'SkillTrace App', 'Node Backend', 'Python ML Script', 'Database Schema'],
      values: [94, 91, 86, 78, 85],
    },
  },

  'skill-assessment': {
    id: 'rep-skill-002',
    type: 'skill-assessment',
    title: 'Adaptive Technical Skill & Domain Proficiency Report',
    subtitle: 'Diagnostic score breakdown across Data Structures, Frontend, Backend, and System Design.',
    score: 91,
    maxScore: 100,
    scoreLabel: 'Overall Skill Index',
    scoreTag: 'Advanced Level',
    status: 'Completed',
    lastGenerated: 'Aug 10, 2026',
    generatedTimeAgo: '2 days ago',
    confidenceLevel: 96,
    badgeColor: 'primary',
    keyInsights: [
      'Demonstrated 94% accuracy in React component lifecycle & hook optimization.',
      'Data Structures & Algorithms score improved from 76% to 88% after recent mock assessments.',
      'Speed percentile: Completed 30 MCQ questions 6 minutes faster than cohort average.',
      'System Design conceptual awareness is solid; database indexing requires deeper practice.',
    ],
    strengths: [
      'React & Modern Frontend Patterns',
      'JavaScript ES6+ Async Programming',
      'REST API Design & Integration',
      'Algorithmic Problem Solving',
    ],
    weaknesses: [
      'Database Indexing & Query Optimization',
      'System Design Caching Strategies (Redis)',
      'Distributed Transaction Patterns',
    ],
    recommendations: [
      {
        id: 'rec-s1',
        title: 'Complete 2 timed mock assessments on Redis & Caching',
        priority: 'High',
        impact: '+ 6 pts',
        category: 'System Design',
        actionText: 'Start Assessment',
      },
      {
        id: 'rec-s2',
        title: 'Review SQL Query Execution Plans and B-Tree Indexing',
        priority: 'High',
        impact: '+ 5 pts',
        category: 'Database',
        actionText: 'Study Modules',
      },
      {
        id: 'rec-s3',
        title: 'Practice Dynamic Programming medium-hard challenges',
        priority: 'Medium',
        impact: '+ 4 pts',
        category: 'DSA',
        actionText: 'Practice Now',
      },
    ],
    subMetrics: [
      { name: 'Frontend Engineering', value: 95, label: '95/100', color: '#0F9D8C' },
      { name: 'Backend Engineering', value: 88, label: '88/100', color: '#3B82F6' },
      { name: 'Data Structures & Algo', value: 88, label: '88/100', color: '#8B5CF6' },
      { name: 'System Architecture', value: 79, label: '79/100', color: '#F5A623' },
    ],
    skillGaps: [
      { skill: 'Redis Caching', impact: 'High', currentLevel: 'Beginner', requiredLevel: 'Intermediate', estHours: 10 },
      { skill: 'Database Query Optimization', impact: 'High', currentLevel: 'Intermediate', requiredLevel: 'Advanced', estHours: 14 },
      { skill: 'Kafka / Event Queues', impact: 'Medium', currentLevel: 'None', requiredLevel: 'Basic', estHours: 12 },
    ],
    chartData: {
      type: 'bar',
      labels: ['Frontend', 'Backend', 'DSA & Logic', 'Database', 'System Design', 'Core CS'],
      values: [95, 88, 88, 82, 79, 90],
    },
    secondaryChartData: {
      type: 'doughnut',
      labels: ['Mastered (90%+)', 'Proficient (80-89%)', 'Developing (60-79%)', 'Needs Focus (<60%)'],
      values: [45, 35, 15, 5],
    },
  },

  'career-recommendation': {
    id: 'rep-career-003',
    type: 'career-recommendation',
    title: 'AI Career Path & Target Role Fit Intelligence',
    subtitle: 'Algorithmic alignment score across tech industry roles, compensation bands, and trajectory.',
    score: 94,
    maxScore: 100,
    scoreLabel: 'Target Role Fit Index',
    scoreTag: 'Optimal Match',
    status: 'Completed',
    lastGenerated: 'Aug 12, 2026',
    generatedTimeAgo: '4 hours ago',
    confidenceLevel: 98,
    badgeColor: 'success',
    keyInsights: [
      '94% fit alignment for Full Stack Engineer (Frontend-leaning) roles.',
      'Strong secondary match (88%) for Software Development Engineer (SDE-1) at Tier-1 product tech companies.',
      'Estimated starting compensation band: ₹12 LPA – ₹18 LPA based on current skill index.',
      'Key accelerator: Completing 1 cloud deployment project elevates top-tier match by 8%.',
    ],
    strengths: [
      'High Full-Stack Product Versatility',
      'Clean Code & Component Modularization',
      'Strong UX Sensibility & Responsiveness',
      'Fast Technology Adoption Rate',
    ],
    weaknesses: [
      'Limited Cloud Infrastructure Exposure',
      'Lack of High-Scale Load Testing Data',
      'Few Open Source Contributions',
    ],
    recommendations: [
      {
        id: 'rec-c1',
        title: 'Target SDE-1 & Full Stack Engineer applications',
        priority: 'High',
        impact: 'Direct Match',
        category: 'Career Path',
        actionText: 'View Companies',
      },
      {
        id: 'rec-c2',
        title: 'Publish flagship full-stack app on AWS / Vercel + Supabase',
        priority: 'High',
        impact: '+ 8% Salary Boost',
        category: 'Project',
        actionText: 'Deploy App',
      },
      {
        id: 'rec-c3',
        title: 'Participate in 1 open-source repository sprint',
        priority: 'Medium',
        impact: 'Resume Standout',
        category: 'Open Source',
        actionText: 'Find Projects',
      },
    ],
    subMetrics: [
      { name: 'Full Stack Engineer', value: 94, label: '94% Match', color: '#0F9D8C' },
      { name: 'Frontend Lead / Developer', value: 92, label: '92% Match', color: '#3B82F6' },
      { name: 'Software Engineer (SDE-1)', value: 88, label: '88% Match', color: '#8B5CF6' },
      { name: 'Cloud / DevOps Engineer', value: 68, label: '68% Match', color: '#F5A623' },
    ],
    skillGaps: [
      { skill: 'AWS / Cloud Deployment', impact: 'High', currentLevel: 'Beginner', requiredLevel: 'Intermediate', estHours: 16 },
      { skill: 'System Load Testing (k6/JMeter)', impact: 'Medium', currentLevel: 'None', requiredLevel: 'Basic', estHours: 8 },
      { skill: 'Micro-Frontend Architecture', impact: 'Low', currentLevel: 'Beginner', requiredLevel: 'Intermediate', estHours: 10 },
    ],
    chartData: {
      type: 'horizontalBar',
      labels: ['Full Stack Eng.', 'Frontend Dev.', 'SDE-1 (Tier-1)', 'Backend Dev.', 'AI Web Dev.'],
      values: [94, 92, 88, 84, 80],
    },
    secondaryChartData: {
      type: 'line',
      labels: ['Sem 4', 'Sem 5', 'Sem 6', 'Sem 7 (Current)', 'Target Sem 8'],
      values: [68, 75, 83, 89, 95],
    },
  },

  'placement-prediction': {
    id: 'rep-placement-004',
    type: 'placement-prediction',
    title: 'AI Placement Probability & Interview Readiness Model',
    subtitle: 'Predictive analytics based on cohort benchmarks, company hiring criteria, and interview scores.',
    score: 88,
    maxScore: 100,
    scoreLabel: 'Placement Probability',
    scoreTag: 'High Likelihood',
    status: 'Completed',
    lastGenerated: 'Aug 09, 2026',
    generatedTimeAgo: '3 days ago',
    confidenceLevel: 95,
    badgeColor: 'amber',
    keyInsights: [
      '88% statistical likelihood of securing a Tier-1 or Tier-2 tech placement within campus drive week 1.',
      'Interview Readiness Index stands at 92/100 for technical rounds and 84/100 for HR / System Design rounds.',
      'Target Company Match: 95% compatibility with Fintech and Product SaaS firms.',
      'Benchmark Percentile: Ranked in the 92nd percentile among 450 Computer Science cohort peers.',
    ],
    strengths: [
      'Top 8% Cohort Algorithmic Score',
      'Solid Technical Live Coding Track Record',
      'High Project Execution Confidence',
      'Excellent Portfolio Presentation',
    ],
    weaknesses: [
      'Mock HR Behavioral Interview Speed',
      'High-Scale System Architecture Under Pressure',
      'Complex Dynamic Programming Speed',
    ],
    recommendations: [
      {
        id: 'rec-pl1',
        title: 'Schedule 2 AI Mock Technical & HR Video Interviews',
        priority: 'High',
        impact: '+ 7% Readiness',
        category: 'Interview',
        actionText: 'Schedule Mock',
      },
      {
        id: 'rec-pl2',
        title: 'Solve 15 Tier-1 Company specific coding problems',
        priority: 'High',
        impact: '+ 5% Pass Rate',
        category: 'Coding',
        actionText: 'Start Problems',
      },
      {
        id: 'rec-pl3',
        title: 'Refine 2-minute elevator pitch for STAR method questions',
        priority: 'Medium',
        impact: 'HR Edge',
        category: 'Behavioral',
        actionText: 'Practice Pitch',
      },
    ],
    subMetrics: [
      { name: 'Tier 1 Tech Product Match', value: 82, label: '82%', color: '#0F9D8C' },
      { name: 'Tier 2 SaaS / Enterprise Match', value: 95, label: '95%', color: '#3B82F6' },
      { name: 'Technical Round Clearing Prob.', value: 91, label: '91%', color: '#8B5CF6' },
      { name: 'HR & Cultural Fit Readiness', value: 84, label: '84%', color: '#F5A623' },
    ],
    skillGaps: [
      { skill: 'STAR Method Behavioral Answers', impact: 'High', currentLevel: 'Intermediate', requiredLevel: 'Mastered', estHours: 6 },
      { skill: 'High Availability System Design', impact: 'High', currentLevel: 'Intermediate', requiredLevel: 'Advanced', estHours: 15 },
      { skill: 'Live Pair Programming Communication', impact: 'Medium', currentLevel: 'Good', requiredLevel: 'Exceptional', estHours: 8 },
    ],
    chartData: {
      type: 'line',
      labels: ['Week 1', 'Week 2', 'Week 3', 'Week 4', 'Week 5', 'Week 6 (Current)'],
      values: [65, 72, 78, 81, 85, 88],
    },
    secondaryChartData: {
      type: 'bar',
      labels: ['Tier 1 Tech', 'Mid-Cap Product', 'High-Growth SaaS', 'Fintech Heavy', 'IT Consulting'],
      values: [82, 94, 95, 90, 98],
    },
  },
};

export const reportHistoryData = [
  {
    id: 'rep-hist-001',
    title: 'AI Career Path & Target Role Fit Intelligence',
    type: 'career-recommendation',
    typeName: 'Career Recommendation',
    score: 94,
    status: 'Completed',
    generatedDate: '2026-08-12',
    formattedDate: 'Aug 12, 2026 · 03:45 PM',
    size: '2.4 MB',
  },
  {
    id: 'rep-hist-002',
    title: 'Comprehensive Portfolio Readiness Analysis',
    type: 'portfolio-analysis',
    typeName: 'Portfolio Analysis',
    score: 87,
    status: 'Completed',
    generatedDate: '2026-08-11',
    formattedDate: 'Aug 11, 2026 · 11:20 AM',
    size: '3.1 MB',
  },
  {
    id: 'rep-hist-003',
    title: 'Adaptive Technical Skill & Domain Proficiency Report',
    type: 'skill-assessment',
    typeName: 'Skill Assessment',
    score: 91,
    status: 'Completed',
    generatedDate: '2026-08-10',
    formattedDate: 'Aug 10, 2026 · 06:10 PM',
    size: '1.9 MB',
  },
  {
    id: 'rep-hist-004',
    title: 'AI Placement Probability & Interview Readiness Model',
    type: 'placement-prediction',
    typeName: 'Placement Prediction',
    score: 88,
    status: 'Completed',
    generatedDate: '2026-08-09',
    formattedDate: 'Aug 09, 2026 · 02:15 PM',
    size: '2.8 MB',
  },
  {
    id: 'rep-hist-005',
    title: 'Mid-Term Portfolio Code Audit & GitHub Diagnostic',
    type: 'portfolio-analysis',
    typeName: 'Portfolio Analysis',
    score: 82,
    status: 'Archived',
    generatedDate: '2026-07-28',
    formattedDate: 'Jul 28, 2026 · 10:00 AM',
    size: '2.9 MB',
  },
  {
    id: 'rep-hist-006',
    title: 'Frontend & React Specialization Assessment',
    type: 'skill-assessment',
    typeName: 'Skill Assessment',
    score: 89,
    status: 'Archived',
    generatedDate: '2026-07-15',
    formattedDate: 'Jul 15, 2026 · 04:30 PM',
    size: '1.7 MB',
  },
  {
    id: 'rep-hist-007',
    title: 'Quarterly Career Roadmap & Skill Gap Audit',
    type: 'career-recommendation',
    typeName: 'Career Recommendation',
    score: 90,
    status: 'Archived',
    generatedDate: '2026-07-01',
    formattedDate: 'Jul 01, 2026 · 09:45 AM',
    size: '2.2 MB',
  },
  {
    id: 'rep-hist-008',
    title: 'Pre-Placement Assessment Benchmark Report',
    type: 'placement-prediction',
    typeName: 'Placement Prediction',
    score: 84,
    status: 'Archived',
    generatedDate: '2026-06-18',
    formattedDate: 'Jun 18, 2026 · 05:20 PM',
    size: '2.6 MB',
  },
];
